name: Admin
version: 1
deps:
  - Block

dbix_fixtures:
  conf:
    debug: 0
    config_dir: share/fixtures/1/conf/
  populate:
    users_and_roles:
      directory: share/fixtures/1/users_roles/
      no_deploy: 1