name: Debug
version: 1

deps:
  - TT
  - Plack

Plugin::EnableMiddleware:
  - Debug
  - Debug::CatalystLog
  - StackTrace

Model::DBIC:
  traits:
    - QueryLog
    - FromMigration
  querylog_args:
    passthrough: 0

Debug:
  querylog: 1