name: Wiki
version: 1

deps:
  - Page
  - Formatter
  - Authorization

Plugin::Page:
  debug: 0
  typepage:
    wiki:
      edit: /wiki

Formatter::Dir:
  prefix_url: /myfiles
  whitelisting:
    - /home/dab/dev/perl/Catapulse/t/var/files/
