name: Authentication
version: 1
deps:
  - DBIC
  - TT

catalyst_plugins:
  - +CatalystX::SimpleLogin

Controller::Login:
  traits:
    - Logout
    - WithRedirect
    - RenderAsTTTemplate
  login_form_args:
    authenticate_args:
      active: 1

authentication:
  default_realm: 'members'
  realms:
    members:
      credential:
        class: 'Password'
        password_field: 'password'
        password_type: 'self_check'
      store:
        class: 'DBIx::Class'
        user_model: 'DBIC::User'
        role_relation: 'user_roles'
        role_field: 'name'
        use_userdata_from_session: 1
