name: Page
version: 1

deps:
  - Block
  - Authorization

catalyst_plugins:
  - Page

Plugin::Page:
  debug: 0
  typepage:
    wiki:
      edit: /wiki
      permission: /page/permission

    from_controller:
      permission: /page/permission
