name: Page
version: 1

deps:
  - TemplateTT
  - Authorization

catalyst_plugins:
  - Page

Plugin::Cache:
  backends:
    Page:
      class: 'Cache::FileCache'
      cache_root: "./cache"
      namespace:  "Pages"
      default_expires_in: '8 hours'
      auto_remove_stale: 1
